#! /usr/bin/env python

import argparse
from lib.diff import compare_all, read_map_file


def main():
    parser = argparse.ArgumentParser(
        prog="stratcomp",
        description="compare stratifications",
    )
    parser.add_argument(
        "strat_rootA",
        metavar="rootA",
        help="directory of first stratification set to compare",
    )
    parser.add_argument(
        "strat_rootB",
        metavar="rootB",
        help="directory of second stratification set to compare",
    )
    parser.add_argument("prefix", metavar="prefix", help="prefix of output")
    parser.add_argument(
        "-c",
        "--chrs",
        default=[],
        nargs="+",
        help="chromosomes to include (all if not given)",
    )
    parser.add_argument(
        "-m",
        "--map_path",
        help="path to mapping file",
    )
    parser.add_argument(
        "-r",
        "--rep",
        default=[],
        nargs="+",
        help="replacement strings",
    )
    parser.add_argument(
        "-i",
        "--ignoreA",
        default=[],
        nargs="+",
        help="regular expressions for files to ignore from A",
    )
    parser.add_argument(
        "-j",
        "--ignoreB",
        default=[],
        nargs="+",
        help="regular expressions for files to ignore from B",
    )
    args = parser.parse_args()
    assert len(args.rep) % 2 == 0, "replacement args must be even number"
    mapper = read_map_file(args.map_path) if args.map_path is not None else {}
    compare_all(
        args.strat_rootA,
        args.strat_rootB,
        args.prefix + "_anti.bed",
        args.prefix + "_diagnostics.tsv.gz",
        mapper,
        args.rep,
        args.chrs,
        args.ignoreA,
        args.ignoreB,
    )


main()
